#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# GHOULBOX: the boot / ABOUT artwork as 4-bit alpha bitmaps (run by tools/build.py generate()):
#   GB_LOGO     "GHOULBOX" in Pirata One (assets/fonts/PirataOne-Regular.ttf, SIL OFL 1.1), boot size
#   GB_LOGO_S   the same, ABOUT size (the height of the large UI face's line)
#   GB_SKULL    a skull, drawn here at 4x and scaled down (smooth edges)
# Format as the icons (tools/aa_raster.py): alpha 0..15, 2 px per byte, high nibble first, rows back to
# back; the firmware draws them with cv_alpha in any colour.
#   gen_ghoulbox_art.py OUT.h
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, str(Path(__file__).resolve().parent))
from aa_raster import pack  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "assets/fonts/PirataOne-Regular.ttf"
SS = 4                                                  # supersampling of the drawn art


def logo(max_w, max_h):
    """the word as large as fits max_w x max_h, cropped to its ink"""
    size = max_h * 2
    while True:
        f = ImageFont.truetype(str(FONT), size)
        x0, y0, x1, y1 = f.getbbox("GHOULBOX")
        if x1 - x0 <= max_w and y1 - y0 <= max_h:
            break
        size -= 1
    im = Image.new("L", (x1 - x0 + 2, y1 - y0 + 2), 0)
    ImageDraw.Draw(im).text((1 - x0, 1 - y0), "GHOULBOX", font=f, fill=255)
    return im.crop(im.getbbox())


def skull(w, h):
    """a skull in w x h px: cranium, cheeks, jaw and teeth in ink; sockets, nose and a crack cut out"""
    W, H = w * SS, h * SS
    im = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(im)
    u = W / 56.0                                        # drawn on a 56-unit grid
    def box(x0, y0, x1, y1):
        return [x0 * u, y0 * u, x1 * u, y1 * u]
    d.ellipse(box(4, 2, 52, 44), fill=255)              # the cranium
    d.rounded_rectangle(box(12, 30, 44, 50), radius=6 * u, fill=255)   # cheeks
    for k in range(5):                                  # the teeth
        d.rounded_rectangle(box(15 + k * 5.4, 49, 19 + k * 5.4, 57), radius=1.4 * u, fill=255)
    d.ellipse(box(11, 22, 25, 36), fill=0)              # the sockets
    d.ellipse(box(31, 22, 45, 36), fill=0)
    d.polygon([(28 * u, 36 * u), (24.5 * u, 43 * u), (31.5 * u, 43 * u)], fill=0)   # the nose
    d.line([(36 * u, 4 * u), (33 * u, 10 * u), (37 * u, 14 * u), (34 * u, 19 * u)], fill=0, width=int(1.6 * u))
    return im.resize((w, h), Image.LANCZOS)


def emit(name, im):
    w, h = im.size
    nib = [min(15, (v + 8) // 17) for v in im.tobytes()]
    data = pack(nib)
    rows = [", ".join(f"0x{b:02X}" for b in data[i:i + 20]) for i in range(0, len(data), 20)]
    return ([f"#define {name}_W {w}u", f"#define {name}_H {h}u", f"static const uint8_t {name}[] = {{"] +
            [f"    {r}," for r in rows] + ["};"]), len(data)


def main():
    out = Path(sys.argv[1])
    L = ["/* generated by tools/gen_ghoulbox_art.py: GHOULBOX's boot / ABOUT art, 4-bit alpha (cv_alpha) */"]
    total = 0
    for name, im in (("GB_LOGO", logo(224, 52)), ("GB_LOGO_S", logo(180, 34)), ("GB_SKULL", skull(48, 56))):
        lines, n = emit(name, im)
        L += lines
        total += n
        print(f"ghoulbox art: {name} {im.size[0]} x {im.size[1]}, {n} B")
    out.write_text("\n".join(L) + "\n")
    print(f"ghoulbox art: {total} B -> {out}")


if __name__ == "__main__":
    main()
